id: PEA59DEEE
initial_creation_type: ocr
source_metadata:
  volumes:
    ec45c9f4b43a431c9e3e3ec534addce0:
      base_file: v037.txt
      image_group_id: I1PD95882
      title: འཇམ་དཔལ་རྡོ་རྗེ་བློ་གྲོས་འཕེལ་བ།
      total_pages: 1379
      volume_number: 37
